### ISSUE TITLE
Update id and byUser fields

### ISSUE THREAD

**Issue by gniezen** [DorianScholz/OpenLibre#1]
Hi Dorian,

OpenLibre is currently sending an `id` field that looks like `de.dorianscholz.openlibre:0.2.3`. The `id` field should be 32 alphanumeric characters. Specifically, this will in future be validated on Tidepools' side with a regex of "[0-9a-z]{32}"). For more details on the `id` field, see http://developer.tidepool.org/data-model/device-data/common.html#id.

`byUser` should contain the `userId` of the authenticated user. (http://developer.tidepool.org/data-model/device-data/types/upload.html#byuser)

**Comment by DorianScholz** [comment]
Sorry Gerrit, I have not been able to maintain this anymore for a long time and I am not using the Libre anymore. So I have added a notice to the readme and will archive this repo now.
