### ISSUE TITLE
Build a unique `uploadId`

### ISSUE THREAD

**Issue by pazaan** [DorianScholz/OpenLibre#5]
Currently, `uploadId` is created as `uploadMetadata.setUploadId("upid_" + deviceSerialNumber);`.

However, `uploadIds` should be unique in Tidepool. We have added a constraint in the database that enforces this, meaning that subsequent uploads from OpenLibre could fail.
The Tidepool Uploader creates a hash to the legacy upload service as `"upid_" + md5sum(deviceId + "_" + time).slice(0,12)`.

In an ideal world, OpenLibre shouldn't use the legacy upload mechanism at all - it should use the newer `platform/data` upload mechanism, but in the interim, generating a unique `uploadId` will suffice.

**Comment by DorianScholz** [comment]
Sorry Lennart, I have not been able to maintain this anymore for a long time and I am not using the Libre anymore. So I have added a notice to the readme and will archive this repo now.
